name: bcompare
version: latest
version-script: cat $SNAPCRAFT_STAGE/version
summary: bcompare is a powerful time-saving utility for comparing files & folders.
description: |
 bcompare is a powerful time-saving utility for comparing files and
 folders.
 Use it to manage source code, keep folders in sync, compare program output,
 and validate copies of your data.  bcompare can create a snapshot of a
 live directory structure, and compare it against the live copy at a later
 date.
 bcompare helps you analyze differences in detail and carefully reconcile
 them.  It commands a wide range of file and text operations, as well as script
 commands for automating tasks.

grade: stable
confinement: strict
architectures:
  - build-on: amd64
  - build-on: i386

parts:
  bcompare:
    after:
      - desktop-qt4
    plugin: nil
    override-build: |
      snapcraftctl build
      set -ex
      ver="$(wget https://www.scootersoftware.com/download.php -q -S -O - 2>&1 | grep Version | sed "2,9d;s|,||g;s|build|.|;s| . |.|" | awk '{print $3}')"
      echo $ver > $SNAPCRAFT_STAGE/version

      # Check build ARCH
      ARCHITECTURE=$(dpkg --print-architecture)
      if [ "${ARCHITECTURE}" = "amd64" ]; then
       wget https://www.scootersoftware.com/bcompare-${ver}_amd64.deb && dpkg-deb -xv bcompare-${ver}_amd64.deb .
      elif [ "${ARCHITECTURE}" = "i386" ]; then
       wget https://www.scootersoftware.com/bcompare-${ver}_i386.deb && dpkg-deb -xv bcompare-${ver}_i386.deb .
      else
       echo "ERROR! beyondcompare only produces software for amd64 and i386. Failing the build here."
       exit 1
      fi

      cp -R -p usr $SNAPCRAFT_PART_INSTALL/
      sed -i 's|Icon=bcompare|Icon=/usr/share/pixmaps/bcompare.png|' $SNAPCRAFT_PART_INSTALL/usr/share/applications/bcompare.desktop
      sed -i 's|BC_LIB=/usr/lib/beyondcompare|BC_LIB=$SNAP/usr/lib/beyondcompare|' $SNAPCRAFT_PART_INSTALL/usr/bin/bcompare
      echo "StartupWMClass=BCompare" >> $SNAPCRAFT_PART_INSTALL/usr/share/applications/bcompare.desktop
    build-packages:
      - wget

apps:
  bcompare:
    command: desktop-launch $SNAP/usr/bin/bcompare
    desktop: usr/share/applications/bcompare.desktop
    plugs:
      - desktop
      - home
      - unity7
      - network
